CREATE TABLE IF NOT EXISTS CONVERSAS(
		IMEI           	TEXT   	NOT NULL,
		MENSAGEM       	TEXT    NOT NULL,
		DATA_ENVIO     	REAL    NOT NULL,
		REMETENTE      	INTEGER NOT NULL,
		MENSAGEM_NOVA  	INTEGER NOT NULL);
		
CREATE TABLE IF NOT EXISTS PEDIDOS(
		IMEI 			TEXT 	NOT NULL,
		DATA_PEDIDO		REAL 	NOT NULL,
		CODI_PEDIDO		INTEGER NOT NULL,
		STATUS_PEDIDO	INTEGER NOT NULL,
		VALOR_PEDIDO	REAL	NOT NULL);

CREATE TABLE IF NOT EXISTS PEDIDOS_ITENS(
		CODI_PEDIDO 	INTEGER NOT NULL,
		SEQUENCIAL_ITEM INTEGER NOT NULL,
		CODI_PRODUTO	INTEGER NOT NULL,
		QTDE			INTEGER NOT NULL,
		VALOR_UNITARIO	REAL	NOT NULL);
		
CREATE TABLE IF NOT EXISTS PRODUTOS(
		CODI_PRODUTO 			INTEGER NOT NULL,
		DESCRICAO 				INTEGER NOT NULL,
		PRECO 					REAL 	NOT NULL,
		ATIVO 					INTEGER NOT NULL,
		GRUPO 					TEXT 	NOT NULL,
		UNIDADE_MEDIDA 			TEXT 	NOT NULL,
		QTDE 					REAL 	NOT NULL,
		OBSERVACOES 			TEXT 	NOT NULL,
		DATA_CADASTRO 			REAL 	NOT NULL,
		DATA_ULTIMA_ALTERACAO 	REAL 	NOT NULL,
		CONSTRAINT PK_PRODUTOS 	PRIMARY KEY (CODI_PRODUTO));
		
CREATE TABLE IF NOT EXISTS ADICIONAIS(
		CODI_ADICIONAL 	INTEGER NOT NULL,
		DESCRICAO 		TEXT NOT NULL,
		VALOR 			REAL NOT NULL,
		CONSTRAINT PK_ADICIONAIS PRIMARY KEY (CODI_ADICIONAL));
		
CREATE TABLE IF NOT EXISTS IGREDIENTES_OPCIONAIS(
		CODI_INGREDIENTE 	INTEGER NOT NULL,
		DESCRICAO 			TEXT NOT NULL,
		CONSTRAINT PK_INGREDIENTES_OPCIONAIS PRIMARY KEY (CODI_INGREDIENTE));
		
CREATE TABLE IF NOT EXISTS PRODUTOS_ADICIONAIS(
		CODI_PRODUTO 	INTEGER NOT NULL,
		CODI_ADICIONAL 	INTEGER NOT NULL,
		CONSTRAINT PK_PRODUTOS_ADICIONAIS PRIMARY KEY (CODI_PRODUTO, CODI_ADICIONAL));
		
CREATE TABLE IF NOT EXISTS PRODUTOS_IGREDIENTES_OPIONAIS(
		CODI_PRODUTO 		INTEGER NOT NULL,
		CODI_INGREDIENTE 	INTEGER NOT NULL,
		CONSTRAINT PK_PRODUTOS_IGREDIENTES_OPIONAIS PRIMARY KEY (CODI_PRODUTO, CODI_INGREDIENTE));